### ISSUE TITLE
File type string parameters will not take changes within unreal

### ISSUE THREAD

**Issue by DionBurgoyne** [sideeffects/HoudiniEngineForUnreal-v2#75]
If the user creates a string type file parameter in an HDA for Unreal, the user can change that parameter within unreal, and that change will trigger a recook... but after the cook has completed, the string will go back to its previous value... the user has to hit the three dot button to the right of it, and type any file names in there in order for them to "stick"

**Comment by nanocell** [comment]
We fixed issues related to the string type file parameter not updating correctly. Could you check whether the latest release / daily build fixed these issues for you?

**Comment by DionBurgoyne** [comment]
Fixed!

**Comment by DionBurgoyne** [comment]
This is still happening, not every time, but after editing a string value a few times it stops working
